### ISSUE TITLE
I cannot keep up the connection up

### ISSUE THREAD

**Issue by Sefriol** [ejvr/qmqtt2qml#1]
I tested the connection with http://test.mosquitto.org/, it worked well. Then I started to test with the real API and I'm able to connect to the server, but when I'm subscribing, the server just closes the connection immediately.

I tried the same address with MQTT.JS, and it works. I checked with Wireshark, and topic string is exactly the same, but I'm wondering if I'm missing some configuration parameters for the client.

[API that I'm using](https://digitransit.fi/en/developers/apis/4-realtime-api/vehicle-positions/)

**Comment by ejvr** [comment]
Just wondering, is this a public API? So I can try for myself. If not can
you upload a binary dump of the subscribe message (preferably both qmqtt en
mqtt.js)?

My guess is that qmqtt and the broker disagree about the correct way to
subscribe.

**Comment by Sefriol** [comment]
Yes It's public API, so you can also test it yourself. I will update this comment when I get back to home, incase you need the binary dump.

[WiresharkFile: MQTTFiltered.zip](https://github.com/ejvr/qmqtt2qml/files/1970428/MQTTFiltered.zip)
[wiresharktxtout.txt](https://github.com/ejvr/qmqtt2qml/files/1970434/wiresharktxtout.txt)

**Comment by ejvr** [comment]
No need the create the binary dump. I can reproduce the problem here, and I'm trying to solve it now.

**Comment by ejvr** [comment]
The problem is that the broker you are connecting to appears to insist on setting the _clean session_ flag. I don't know if this is a requirement in of MQTT standard or a quirk of this broker.

You can set this on the MQTT::Client instance using `m_client->setCleanSession(true)` in the C++ code.

**Comment by Sefriol** [comment]
Yep, that did it. Now the messages are getting through! Thank you very much!
